package ppk_test

import (
	"github.com/amiremohamadi/go-ppk"
	"regexp"
	"testing"
)

func TestGeneratePPK(t *testing.T) {
	comment := "Generated by test"
	_, ppk, _ := ppk.GeneratePPK(comment)

	regex := regexp.MustCompile("Comment: .*")
	expected := regex.Find([]byte(ppk))

	if string(expected) != "Comment: Generated by test" {
		t.Fatalf("comment section mismatched")
	}
}
